version: 2
jobs:
  install_deps:
    docker:
      - image: cimg/node:14.17.1 
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            echo "Node version: $(node -v)"
            echo "npm version: $(npm -v)"
            npm install

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  typecheck:
    docker:
      - image: cimg/node:14.17.1
    steps:
      - checkout
      - attach_workspace:
          at: .
      
      - run:
          name: "TypeCheck"
          command: npm run typecheck
      
  lint:
    docker:
      - image: cimg/node:14.17.1
    steps:
      - checkout
      - attach_workspace:
          at: .

      - run:
          name: "Linting"
          command: npm run lint

  test:
    docker:
      - image: cimg/node:14.17.1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Testing"
          command: npm run test

workflows:
  version: 2
  main:
    jobs:
      - install_deps
      - typecheck:
          requires:
            - install_deps
      - lint:
          requires:
            - install_deps
      - test:
          requires:
            - install_deps

